//
// File generated by rootcint at Tue Dec  1 13:09:43 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME pi0_ERToolsPi0TrainDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "pi0_ERToolsPi0TrainDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      namespace ertool {

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::ertool::ERAlgopi0Train ERAlgopi0Train;
      #else
      class ERAlgopi0Train  :  public ::ertool::AlgoBase {
         public:
         //friend XX;
         #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
         typedef ::ertool::ERAlgopi0Train::showerData showerData;
         #else
         class showerData  {
            public:
            //friend XX;
            ::TVector3 start; //
            ::TVector3 dir; //
            ::TVector3 p; //
            double L; //
            double R; //
            double angle; //
            double E; //
            int ID; //
            int PDG; //
         };
         #endif

         // To force the creation of a virtual table, throw just in case.
         virtual ~ERAlgopi0Train() throw() {};
         ::TNtuple* nt; //
         vector< ::TVector3 > nhat; //
         vector< ::TVector3 > r0; //
      };
      #endif
      } 
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void ertoolcLcLERAlgopi0Train_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void ertoolcLcLERAlgopi0Train_Dictionary();
   static void *new_ertoolcLcLERAlgopi0Train(void *p = 0);
   static void *newArray_ertoolcLcLERAlgopi0Train(Long_t size, void *p);
   static void delete_ertoolcLcLERAlgopi0Train(void *p);
   static void deleteArray_ertoolcLcLERAlgopi0Train(void *p);
   static void destruct_ertoolcLcLERAlgopi0Train(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::ertool::ERAlgopi0Train*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::ertool::ERAlgopi0Train) == sizeof( ::ROOTShadow::Shadow::ertool::ERAlgopi0Train));
      ::ertool::ERAlgopi0Train *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::ertool::ERAlgopi0Train),0);
      static ::ROOT::TGenericClassInfo 
         instance("ertool::ERAlgopi0Train", "./ERAlgopi0Train.h", 27,
                  typeid(::ertool::ERAlgopi0Train), ::ROOT::DefineBehavior(ptr, ptr),
                  &ertoolcLcLERAlgopi0Train_ShowMembers, &ertoolcLcLERAlgopi0Train_Dictionary, isa_proxy, 4,
                  sizeof(::ertool::ERAlgopi0Train) );
      instance.SetNew(&new_ertoolcLcLERAlgopi0Train);
      instance.SetNewArray(&newArray_ertoolcLcLERAlgopi0Train);
      instance.SetDelete(&delete_ertoolcLcLERAlgopi0Train);
      instance.SetDeleteArray(&deleteArray_ertoolcLcLERAlgopi0Train);
      instance.SetDestructor(&destruct_ertoolcLcLERAlgopi0Train);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::ertool::ERAlgopi0Train*)
   {
      return GenerateInitInstanceLocal((::ertool::ERAlgopi0Train*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ertool::ERAlgopi0Train*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void ertoolcLcLERAlgopi0Train_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::ertool::ERAlgopi0Train*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

//______________________________________________________________________________
namespace ROOTDict {
   void ertoolcLcLERAlgopi0Train_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class ertool::ERAlgopi0Train.
      typedef ::ROOTShadow::Shadow::ertool::ERAlgopi0Train ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::ertool::ERAlgopi0Train*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nt", &sobj->nt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nhat", (void*)&sobj->nhat);
      R__insp.InspectMember("vector<TVector3>", (void*)&sobj->nhat, "nhat.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "r0", (void*)&sobj->r0);
      R__insp.InspectMember("vector<TVector3>", (void*)&sobj->r0, "r0.", false);
      R__insp.GenericShowMembers("ertool::AlgoBase", ( ::ertool::AlgoBase * )( (::ertool::ERAlgopi0Train*) obj ), false);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_ertoolcLcLERAlgopi0Train(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::ertool::ERAlgopi0Train : new ::ertool::ERAlgopi0Train;
   }
   static void *newArray_ertoolcLcLERAlgopi0Train(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::ertool::ERAlgopi0Train[nElements] : new ::ertool::ERAlgopi0Train[nElements];
   }
   // Wrapper around operator delete
   static void delete_ertoolcLcLERAlgopi0Train(void *p) {
      delete ((::ertool::ERAlgopi0Train*)p);
   }
   static void deleteArray_ertoolcLcLERAlgopi0Train(void *p) {
      delete [] ((::ertool::ERAlgopi0Train*)p);
   }
   static void destruct_ertoolcLcLERAlgopi0Train(void *p) {
      typedef ::ertool::ERAlgopi0Train current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::ertool::ERAlgopi0Train

namespace ROOTDict {
   void vectorlETVector3gR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlETVector3gR_Dictionary();
   static void *new_vectorlETVector3gR(void *p = 0);
   static void *newArray_vectorlETVector3gR(Long_t size, void *p);
   static void delete_vectorlETVector3gR(void *p);
   static void deleteArray_vectorlETVector3gR(void *p);
   static void destruct_vectorlETVector3gR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<TVector3>*)
   {
      vector<TVector3> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TVector3>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<TVector3>", -2, "prec_stl/vector", 49,
                  typeid(vector<TVector3>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlETVector3gR_Dictionary, isa_proxy, 0,
                  sizeof(vector<TVector3>) );
      instance.SetNew(&new_vectorlETVector3gR);
      instance.SetNewArray(&newArray_vectorlETVector3gR);
      instance.SetDelete(&delete_vectorlETVector3gR);
      instance.SetDeleteArray(&deleteArray_vectorlETVector3gR);
      instance.SetDestructor(&destruct_vectorlETVector3gR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<TVector3> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<TVector3>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlETVector3gR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<TVector3>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlETVector3gR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TVector3> : new vector<TVector3>;
   }
   static void *newArray_vectorlETVector3gR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TVector3>[nElements] : new vector<TVector3>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlETVector3gR(void *p) {
      delete ((vector<TVector3>*)p);
   }
   static void deleteArray_vectorlETVector3gR(void *p) {
      delete [] ((vector<TVector3>*)p);
   }
   static void destruct_vectorlETVector3gR(void *p) {
      typedef vector<TVector3> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<TVector3>

/********************************************************
* pi0_ERToolsPi0TrainDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablepi0_ERToolsPi0TrainDict();

extern "C" void G__set_cpp_environmentpi0_ERToolsPi0TrainDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("ERAlgopi0Train.h");
  G__cpp_reset_tagtablepi0_ERToolsPi0TrainDict();
}
#include <new>
extern "C" int G__cpp_dllrevpi0_ERToolsPi0TrainDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ertool::ERAlgopi0Train */
static int G__pi0_ERToolsPi0TrainDict_707_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ertool::ERAlgopi0Train* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ertool::ERAlgopi0Train(*(string*) libp->para[0].ref);
     } else {
       p = new((void*) gvp) ertool::ERAlgopi0Train(*(string*) libp->para[0].ref);
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new ertool::ERAlgopi0Train[n];
       } else {
         p = new((void*) gvp) ertool::ERAlgopi0Train[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new ertool::ERAlgopi0Train;
       } else {
         p = new((void*) gvp) ertool::ERAlgopi0Train;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__pi0_ERToolsPi0TrainDict_707_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ertool::ERAlgopi0Train* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ertool::ERAlgopi0Train(*(ertool::ERAlgopi0Train*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ertool::ERAlgopi0Train G__TertoolcLcLERAlgopi0Train;
static int G__pi0_ERToolsPi0TrainDict_707_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ertool::ERAlgopi0Train*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ertool::ERAlgopi0Train*) (soff+(sizeof(ertool::ERAlgopi0Train)*i)))->~G__TertoolcLcLERAlgopi0Train();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ertool::ERAlgopi0Train*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ertool::ERAlgopi0Train*) (soff))->~G__TertoolcLcLERAlgopi0Train();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__pi0_ERToolsPi0TrainDict_707_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ertool::ERAlgopi0Train* dest = (ertool::ERAlgopi0Train*) G__getstructoffset();
   *dest = *(ertool::ERAlgopi0Train*) libp->para[0].ref;
   const ertool::ERAlgopi0Train& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ertool::ERAlgopi0Train */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncpi0_ERToolsPi0TrainDict {
 public:
  G__Sizep2memfuncpi0_ERToolsPi0TrainDict(): p(&G__Sizep2memfuncpi0_ERToolsPi0TrainDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncpi0_ERToolsPi0TrainDict::*p)();
};

size_t G__get_sizep2memfuncpi0_ERToolsPi0TrainDict()
{
  G__Sizep2memfuncpi0_ERToolsPi0TrainDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancepi0_ERToolsPi0TrainDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train))) {
     ertool::ERAlgopi0Train *G__Lderived;
     G__Lderived=(ertool::ERAlgopi0Train*)0x1000;
     {
       ertool::AlgoBase *G__Lpbase=(ertool::AlgoBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train),G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLAlgoBase),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       ertool::UnitBase *G__Lpbase=(ertool::UnitBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train),G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLUnitBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       ertool::MessageUtil *G__Lpbase=(ertool::MessageUtil*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train),G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLMessageUtil),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablepi0_ERToolsPi0TrainDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<PSet::KeyChar_t,size_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_pairlEfcllitecLcLPSetcLcLKeyChar_tcOunsignedsPlonggR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::string>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,::fcllite::PSet>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,::fcllite::PSet>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,fcllite::PSet>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,fcllite::PSet,less<string> >",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<size_t,std::string>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_pairlEunsignedsPlongcOstringgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<NodeID_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertool));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Combination_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<unsigned long,allocator<unsigned long> > >",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<geoalgo::Vector>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<double> >",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<geoalgo::Point_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("numeric_limits<size_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_numeric_limitslEunsignedsPlonggR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ertool::Shower>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ertool::Track>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ertool::Flash>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ertool::RecoInputID_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned long,string> >",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<::ertool::NodeID_t>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("deque<::ertool::Particle>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_dequelEertoolcLcLParticlecOallocatorlEertoolcLcLParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("deque<ertool::Particle>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_dequelEertoolcLcLParticlecOallocatorlEertoolcLcLParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVector3>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ertool::ERAlgopi0Train */
static void G__setup_memvarertoolcLcLERAlgopi0Train(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train));
   { ertool::ERAlgopi0Train *p; p=(ertool::ERAlgopi0Train*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->nt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_TNtuple),-1,-1,1,"nt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nhat)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR),G__defined_typename("vector<TVector3>"),-1,1,"nhat=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->r0)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR),G__defined_typename("vector<TVector3>"),-1,1,"r0=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarpi0_ERToolsPi0TrainDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncertoolcLcLERAlgopi0Train(void) {
   /* ertool::ERAlgopi0Train */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train));
   G__memfunc_setup("ERAlgopi0Train",1313,G__pi0_ERToolsPi0TrainDict_707_0_1, 105, G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train), -1, 0, 1, 1, 1, 0, "u 'string' - 11 '\"ERAlgopi0Train\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reset",515,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AcceptPSet",972,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'fcllite::PSet' - 11 - cfg", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ProcessBegin",1220,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Reconstruct",1180,(G__InterfaceMethod) NULL,103, -1, -1, 0, 2, 1, 1, 0, 
"u 'ertool::EventData' - 11 - data u 'ertool::ParticleGraph' - 1 - graph", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ProcessEnd",1014,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TFile' - 0 'nullptr' fout", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("ERAlgopi0Train", 1313, G__pi0_ERToolsPi0TrainDict_707_0_7, (int) ('i'), G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train), -1, 0, 1, 1, 1, 0, "u 'ertool::ERAlgopi0Train' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ERAlgopi0Train", 1439, G__pi0_ERToolsPi0TrainDict_707_0_8, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__pi0_ERToolsPi0TrainDict_707_0_9, (int) ('u'), G__get_linked_tagnum(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train), -1, 1, 1, 1, 1, 0, "u 'ertool::ERAlgopi0Train' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncpi0_ERToolsPi0TrainDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalpi0_ERToolsPi0TrainDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {
}

static void G__cpp_setup_func35() {
}

static void G__cpp_setup_func36() {
}

static void G__cpp_setup_func37() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcpi0_ERToolsPi0TrainDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
  G__cpp_setup_func35();
  G__cpp_setup_func36();
  G__cpp_setup_func37();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR = { "vector<unsigned long,allocator<unsigned long> >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_fcllite = { "fcllite" , 110 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_fcllitecLcLPSet = { "fcllite::PSet" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_pairlEfcllitecLcLPSetcLcLKeyChar_tcOunsignedsPlonggR = { "pair<fcllite::PSet::KeyChar_t,unsigned long>" , 115 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR = { "map<string,fcllite::PSet,less<string>,allocator<pair<const string,fcllite::PSet> > >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_ertool = { "ertool" , 110 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_pairlEunsignedsPlongcOstringgR = { "pair<unsigned long,string>" , 115 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR = { "vector<vector<unsigned long,allocator<unsigned long> >,allocator<vector<unsigned long,allocator<unsigned long> > > >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<unsigned long,allocator<unsigned long> >,allocator<vector<unsigned long,allocator<unsigned long> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLMessageUtil = { "ertool::MessageUtil" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLUnitBase = { "ertool::UnitBase" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_numeric_limitslEunsignedsPlonggR = { "numeric_limits<unsigned long>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR = { "vector<geoalgo::Vector,allocator<geoalgo::Vector> >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<geoalgo::Vector,allocator<geoalgo::Vector> >::iterator>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLEventData = { "ertool::EventData" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgR = { "vector<ertool::Shower,allocator<ertool::Shower> >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ertool::Shower,allocator<ertool::Shower> >::iterator>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgR = { "vector<ertool::Track,allocator<ertool::Track> >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ertool::Track,allocator<ertool::Track> >::iterator>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgR = { "vector<ertool::Flash,allocator<ertool::Flash> >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ertool::Flash,allocator<ertool::Flash> >::iterator>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR = { "vector<pair<unsigned long,string>,allocator<pair<unsigned long,string> > >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned long,string>,allocator<pair<unsigned long,string> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLParticleGraph = { "ertool::ParticleGraph" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_dequelEertoolcLcLParticlecOallocatorlEertoolcLcLParticlegRsPgR = { "deque<ertool::Particle,allocator<ertool::Particle> >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLAlgoBase = { "ertool::AlgoBase" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_TNtuple = { "TNtuple" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train = { "ertool::ERAlgopi0Train" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR = { "vector<TVector3,allocator<TVector3> >" , 99 , -1 };
G__linked_taginfo G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVector3,allocator<TVector3> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablepi0_ERToolsPi0TrainDict() {
  G__pi0_ERToolsPi0TrainDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_string.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TFile.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_fcllite.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_fcllitecLcLPSet.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_pairlEfcllitecLcLPSetcLcLKeyChar_tcOunsignedsPlonggR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_ertool.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_pairlEunsignedsPlongcOstringgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLMessageUtil.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLUnitBase.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_numeric_limitslEunsignedsPlonggR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLEventData.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLParticleGraph.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_dequelEertoolcLcLParticlecOallocatorlEertoolcLcLParticlegRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLAlgoBase.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_TNtuple.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR.tagnum = -1 ;
  G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablepi0_ERToolsPi0TrainDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_string);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_fcllite);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_fcllitecLcLPSet);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_pairlEfcllitecLcLPSetcLcLKeyChar_tcOunsignedsPlonggR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_ertool);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_pairlEunsignedsPlongcOstringgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLMessageUtil);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLUnitBase);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_numeric_limitslEunsignedsPlonggR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLEventData);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLParticleGraph);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_dequelEertoolcLcLParticlecOallocatorlEertoolcLcLParticlegRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLAlgoBase);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_TNtuple);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_ertoolcLcLERAlgopi0Train),sizeof(ertool::ERAlgopi0Train),-1,263424,(char*)NULL,G__setup_memvarertoolcLcLERAlgopi0Train,G__setup_memfuncertoolcLcLERAlgopi0Train);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR);
   G__get_linked_tagnum_fwd(&G__pi0_ERToolsPi0TrainDictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setuppi0_ERToolsPi0TrainDict(void) {
  G__check_setup_version(30051515,"G__cpp_setuppi0_ERToolsPi0TrainDict()");
  G__set_cpp_environmentpi0_ERToolsPi0TrainDict();
  G__cpp_setup_tagtablepi0_ERToolsPi0TrainDict();

  G__cpp_setup_inheritancepi0_ERToolsPi0TrainDict();

  G__cpp_setup_typetablepi0_ERToolsPi0TrainDict();

  G__cpp_setup_memvarpi0_ERToolsPi0TrainDict();

  G__cpp_setup_memfuncpi0_ERToolsPi0TrainDict();
  G__cpp_setup_globalpi0_ERToolsPi0TrainDict();
  G__cpp_setup_funcpi0_ERToolsPi0TrainDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncpi0_ERToolsPi0TrainDict();
  return;
}
class G__cpp_setup_initpi0_ERToolsPi0TrainDict {
  public:
    G__cpp_setup_initpi0_ERToolsPi0TrainDict() { G__add_setup_func("pi0_ERToolsPi0TrainDict",(G__incsetup)(&G__cpp_setuppi0_ERToolsPi0TrainDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initpi0_ERToolsPi0TrainDict() { G__remove_setup_func("pi0_ERToolsPi0TrainDict"); }
};
G__cpp_setup_initpi0_ERToolsPi0TrainDict G__cpp_setup_initializerpi0_ERToolsPi0TrainDict;

